name: Sync to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: env.SSH_HOST && env.SSH_USERNAME && env.SSH_PASSWORD
    steps:
      - name: SSH and deploy node app
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            password: ${{ secrets.SSH_PASSWORD }}
            port: ${{ secrets.SSH_PORT || '22' }}
            fail_on_stderr: true
            script: |
                cd /app/YGeeker-Website
                rm -rf yarn.lock
                git pull origin master
                yarn --production
                yarn run build
                kill $(lsof -t -i:3000)
                pm2 restart 0 || pm2 start yarn --name "YGeeker-Website" -- start
