name: Sync to Server

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "16"

            - name: SSH and deploy node app
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  password: ${{ secrets.SSH_PASSWORD }}
                  port: ${{ secrets.SSH_PORT || '22' }}
                  fail_on_stderr: true
                  script: |
                      cd /home/app/YGeeker_Website
                      rm -rf yarn.lock
                      git pull origin main

                      # Adapt config for China site
                      node adapt-for-china-site.js

                      yarn --production
                      yarn run build
                      kill $(lsof -t -i:3000)
                      pm2 list | grep "ygeeker-website" && pm2 reload "ygeeker-website" || pm2 start yarn --name "ygeeker-website" -- start
