name: Sync to Server

on:
    push:
        branches:
            - main

jobs:
    deploy:
        if: ${{ false }}
        runs-on: ubuntu-latest

        steps:
            - name: SSH and deploy node app
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  password: ${{ secrets.SSH_PASSWORD }}
                  port: ${{ secrets.SSH_PORT }}
                  script: |
                      cd /app/YGeeker-Website
                      rm -rf package-lock.json
                      git pull origin master
                      npm install --production
                      npm run build
                      kill $(lsof -t -i:3000)
                      pm2 restart 0 || pm2 start npm --name "YGeeker-Website" -- start
